#!/bin/bash

####
# T.J.Blätte
# 2016
####
#
# Wrapper for gene set enrichment analysis with
#       Broad Institute's GSEA java application.
#       Preranks DESeq2 outputs based on estimates
#       log2 fold changes and runs GSEA for each
#       of the gene set collections provided.
#       Note: GSEA does not accept hyphens in any
#       of the input file names!
#
# Args:
#   IN: Name of / Path to the DESeq2 output file
#       containing each gene's log2 fold change.
#       (*woutNA.txt)
#   [..]: *gmt files defining the gene set collections
#       to be tested. Can be downloaded from MSigDB
#       or custom-built.
#
# Hardcoded files:
#   DB: Database file to convert ensembl IDs from DESeq2
#       output to HUGO gene symbols from MSigDB's GMT files.
#   GSEA_JAR: Path to the GSEA jar file, version 3.0.
#
# Output:
#   $PWD/{month-day}: Folder containing all the GSEA
#       output files generated by analyses started on
#       a given day. Each analysis is placed in its
#       own subfolder.
#
####

IN="$1"
DB="/NGS/known_sites/hg19/biomart_ensembl74ID_to_HUGOsymbol_mapped.txt"
GSEA_JAR="/NGS/gsea/newest/gsea-3.0.jar"

# Annotate results from DEG analysis with HUGO gene symbols to match gene identifiers in GSEA gene sets
#  $DB contains ENSEMBL IDs in column 1 and HUGO gene symbols in column 2
#  ENSEMBL IDs that could not be mapped to a HUGO gene symbol have already been removed
#  --> process old and new DESeq2 output files
#    old files contain ensembl ID in column 1
#    new files contain ensembl ID and gene symbol, joined by an underscore
if [ "$(head -n1 "$IN" | cut -f1)" == "geneID_geneSymbol" ]
then
    join -t '	'  <(tail -n +2 $DB | sort -k1,1b) <(tail -n +2 $IN | sed 's/\.[^\t]*//' | sort -k1,1b) > ${IN%.txt}_geneSymbols.txt

    # Prepare preranked gene list for GSEA
    #  Here: $2 = HUGO gene symbol, $4 = logFC
    awk -v OFS='\t'	'{print($2,$4)}' ${IN%.txt}_geneSymbols.txt > ${IN%.txt}_forGSEA_lfc.rnk
else
    join -t '	'  <(tail -n +2 $DB | sort -k1,1b) <(tail -n +2 $IN | sort -k1,1b) > ${IN%.txt}_geneSymbols.txt

    # Prepare preranked gene list for GSEA
    #  Here: $2 = HUGO gene symbol, $5 = logFC
    awk -v OFS='\t'	'{print($2,$5)}' ${IN%.txt}_geneSymbols.txt > ${IN%.txt}_forGSEA_lfc.rnk
fi


# Run GSEA once for each gene set
# GSEA will fail if JAVA tmp folder does not exist -> create it now
mkdir -p JAVA_TMP
shift 1
while [[ $# > 0 ]]
do
    set=$1
    java -cp $GSEA_JAR -Xmx1024m xtools.gsea.GseaPreranked \
            -gmx $set \
            -norm meandiv \
            -nperm 1000 \
            -rnk ${IN%.txt}_forGSEA_lfc.rnk \
            -scoring_scheme weighted \
            -rpt_label "$(basename ${IN})_$(basename ${set})_lfc"  \
            -create_svgs true \
            -make_sets true \
            -plot_top_x 50 \
            -rnd_seed timestamp \
            -set_max 500 \
            -set_min 15 \
            -zip_report false \
            -gui false
            #-scoring_scheme classic \
    shift 1
done



